"""Initial migration with all models

Revision ID: 2bf57d464356
Revises: 
Create Date: 2025-12-10 12:42:57.234398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf57d464356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_papers_exam_type'), ['exam_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_papers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_papers_is_published'), ['is_published'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('chapter', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_exam_type'), ['exam_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject'), ['subject'], unique=False)

    op.create_table('study_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('study_duration', sa.Integer(), nullable=False),
    sa.Column('exam_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    with op.batch_alter_table('study_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_statistics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_statistics_user_id'), ['user_id'], unique=False)

    op.create_table('exam_paper_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'order', name='uq_paper_order'),
    sa.UniqueConstraint('paper_id', 'question_id', name='uq_paper_question')
    )
    with op.batch_alter_table('exam_paper_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_paper_questions_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_paper_questions_question_id'), ['question_id'], unique=False)

    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_sessions_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('practice_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(length=500), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_records_is_correct'), ['is_correct'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_records_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_records_user_id'), ['user_id'], unique=False)

    op.create_table('wrong_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question')
    )
    with op.batch_alter_table('wrong_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wrong_questions_mastered'), ['mastered'], unique=False)
        batch_op.create_index(batch_op.f('ix_wrong_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wrong_questions_user_id'), ['user_id'], unique=False)

    op.create_table('exam_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_results_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_results_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_exam_results_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_results_session_id'))
        batch_op.drop_index(batch_op.f('ix_exam_results_paper_id'))

    op.drop_table('exam_results')
    with op.batch_alter_table('wrong_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wrong_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_wrong_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_wrong_questions_mastered'))

    op.drop_table('wrong_questions')
    with op.batch_alter_table('practice_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_practice_records_question_id'))
        batch_op.drop_index(batch_op.f('ix_practice_records_is_correct'))
        batch_op.drop_index(batch_op.f('ix_practice_records_created_at'))

    op.drop_table('practice_records')
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_exam_sessions_paper_id'))

    op.drop_table('exam_sessions')
    with op.batch_alter_table('exam_paper_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_paper_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_exam_paper_questions_paper_id'))

    op.drop_table('exam_paper_questions')
    with op.batch_alter_table('study_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_statistics_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_statistics_date'))

    op.drop_table('study_statistics')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_question_type'))
        batch_op.drop_index(batch_op.f('ix_questions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_questions_exam_type'))
        batch_op.drop_index(batch_op.f('ix_questions_chapter'))

    op.drop_table('questions')
    with op.batch_alter_table('exam_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_papers_is_published'))
        batch_op.drop_index(batch_op.f('ix_exam_papers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_exam_papers_exam_type'))

    op.drop_table('exam_papers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
